[package]
name = "slice-string"
version = "0.4.0"
edition = "2021"
description = "A String backed by a slice"
license = "MIT"
repository = "https://github.com/quartiq/slice-string"
keywords = ["string", "vec", "no_std", "no-std"]

[dependencies]
tinyvec = "1.6.0"
